Fix the reference genome format.
python3: can't open file '/data-weedomics-1/align_fastq/modules/../scripts/fix_Reference_genome_format.py': [Errno 2] No such file or directory
